### ISSUE TITLE
你好, 数据库好像是少了t_echarts这张表 有时间可以提交一下吗

### ISSUE THREAD

**Issue by HowlJo** [kirito66465/pack-java#3]

**Comment by kirito66465** [comment]
我记得配置是支持自动建表的诶，如果没有可以按照实体类手动建一下的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kirito66465/pack-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月24日(星期二) 下午3:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [kirito66465/pack-java] 你好, 数据库好像是少了t_echarts这张表 有时间可以提交一下吗 (Issue #3)





 
Closed #3 as not planned.
